# Generated by Django 3.0.3 on 2020-03-15 01:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('reactbackapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True, null=True)),
                ('image', models.ImageField(blank=True, null=True, upload_to='')),
            ],
        ),
        migrations.AddField(
            model_name='user',
            name='avatar',
            field=models.FilePathField(default=None),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='user',
            name='token',
            field=models.CharField(blank=True, default='eda451b5ced643cb89d4dd1ef5698c74', max_length=255, null=True),
        ),
        migrations.CreateModel(
            name='Operation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('operation_product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='reactbackapp.Product')),
                ('operation_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='reactbackapp.User')),
            ],
        ),
    ]
