# Generated by Django 3.0.3 on 2020-03-15 01:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reactbackapp', '0002_auto_20200315_0233'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='avatar',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
        migrations.AlterField(
            model_name='user',
            name='token',
            field=models.CharField(blank=True, default='618b205d2dc7454896e31e22a12d5ee2', max_length=255, null=True),
        ),
    ]
