# Generated by Django 3.0.3 on 2020-03-15 01:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reactbackapp', '0003_auto_20200315_0234'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='token',
            field=models.CharField(blank=True, default='435e1535bd01450c968808cb1043bfea', max_length=255, null=True),
        ),
    ]
