# Generated by Django 3.0.3 on 2020-03-15 12:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reactbackapp', '0008_auto_20200315_1327'),
    ]

    operations = [
        migrations.AlterField(
            model_name='myuser',
            name='avatar',
            field=models.ImageField(blank=True, null=True, upload_to='static/upload/users'),
        ),
        migrations.AlterField(
            model_name='myuser',
            name='token',
            field=models.CharField(blank=True, default='54f4b5d5bbc744ad9e9501eb564a44cc', max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='static/upload/products'),
        ),
    ]
