# Generated by Django 3.0.3 on 2020-03-15 16:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reactbackapp', '0009_auto_20200315_1330'),
    ]

    operations = [
        migrations.RenameField(
            model_name='operation',
            old_name='title',
            new_name='type',
        ),
        migrations.AlterField(
            model_name='myuser',
            name='token',
            field=models.CharField(blank=True, default='9bd79fd4de324309a9ce9cd345d5edde', max_length=255, null=True),
        ),
    ]
