# Generated by Django 3.0.3 on 2020-03-15 16:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('reactbackapp', '0010_auto_20200315_1709'),
    ]

    operations = [
        migrations.AlterField(
            model_name='myuser',
            name='token',
            field=models.CharField(blank=True, default='d6a66f394b8842e0aa3fe5bae7b19f8f', max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='operation',
            name='operation_user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='reactbackapp.MyUser'),
        ),
    ]
