# Generated by Django 3.0.3 on 2020-03-15 16:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reactbackapp', '0011_auto_20200315_1715'),
    ]

    operations = [
        migrations.AlterField(
            model_name='myuser',
            name='token',
            field=models.CharField(blank=True, default='3ef0d20d7d924e1eb1d4ca1cf6cbac30', max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='operation',
            name='type',
            field=models.SmallIntegerField(blank=True, choices=[(1, 'Input'), (2, 'Output')], max_length=255, null=True),
        ),
    ]
