# Generated by Django 3.0.3 on 2020-03-15 16:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reactbackapp', '0012_auto_20200315_1740'),
    ]

    operations = [
        migrations.AddField(
            model_name='operation',
            name='quantity',
            field=models.SmallIntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='myuser',
            name='token',
            field=models.CharField(blank=True, default='2f0671b3bce647cf9824f7e92a085389', max_length=255, null=True),
        ),
    ]
