# Generated by Django 3.0.3 on 2020-03-15 18:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reactbackapp', '0013_auto_20200315_1741'),
    ]

    operations = [
        migrations.AlterField(
            model_name='myuser',
            name='avatar',
            field=models.ImageField(blank=True, null=True, upload_to='upload/users'),
        ),
        migrations.AlterField(
            model_name='myuser',
            name='token',
            field=models.CharField(blank=True, default='60096076707b423593feb931e4648e5a', max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='upload/products'),
        ),
    ]
