# Generated by Django 3.0.3 on 2020-03-15 21:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reactbackapp', '0014_auto_20200315_1905'),
    ]

    operations = [
        migrations.AlterField(
            model_name='myuser',
            name='token',
            field=models.CharField(blank=True, default='fe2e7f9fb83e4300bc65d7ef25a0eb38', max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='operation',
            name='type',
            field=models.SmallIntegerField(blank=True, choices=[(1, 'Input'), (2, 'Output')], null=True),
        ),
    ]
